/*
 * Copyright (c) 2026 Purushottam <purushottam@passiveintent.dev>
 *
 * This source code is licensed under the AGPL-3.0-only license found in the
 * LICENSE file in the root directory of this source tree.
 */

package recover

import (
	"encoding/json"
	"math"
	"os"
	"testing"

	"github.com/purushpsm147/palimpsest/pkg/sketch"
	"github.com/purushpsm147/palimpsest/pkg/wire"
)

// TestGoldenVectors cross-checks this package against vectors produced by
// the Python conformance oracle (oracle/README.md, `make golden`):
// recovery_case1.json (a single large solve) and recovery_watermark.json
// (a watermark/repair pair). Both were generated by the oracle's own FISTA
// + debias implementation over the same y — Go's independent solver is
// checked against the *ground truth* planted support/residuals in each
// file (recall/RMSE thresholds, ADR-002 acceptance criteria), not against
// the oracle's specific recovered values, since FISTA's Lipschitz estimate
// depends on a power-iteration starting vector that differs between the
// two implementations' RNGs.
//
// docs/adr/ADR-001: "Python feasibility harness promoted to conformance
// oracle generating golden vectors Go must match byte-exact." (Recover's
// numerical solve is the one exception documented here: matched against
// acceptance thresholds, not bytes — see docs/SPEC.md's Recovery section.)
func TestGoldenVectors(t *testing.T) {
	t.Run("recovery_case1", testGoldenRecoveryCase1)
	t.Run("recovery_watermark", testGoldenRecoveryWatermark)
}

type goldenSupportEntry struct {
	Index    int     `json:"index"`
	ID       uint64  `json:"id"`
	Name     string  `json:"name"`
	Residual float64 `json:"residual"`
}

type recoveryCase1File struct {
	M          int                  `json:"m"`
	D          int                  `json:"d"`
	K          int                  `json:"k"`
	Seed       uint64               `json:"seed"`
	Lambda     float64              `json:"lambda"`
	Threshold  float64              `json:"threshold"`
	Iters      int                  `json:"iters"`
	PowerIters int                  `json:"power_iters"`
	Names      []string             `json:"names"`
	Support    []goldenSupportEntry `json:"support"`
	Y          []float64            `json:"y"`
}

func testGoldenRecoveryCase1(t *testing.T) {
	var f recoveryCase1File
	loadGoldenJSON(t, "recovery_case1.json", &f)
	if len(f.Support) != f.K {
		t.Fatalf("recovery_case1.json: len(support)=%d != k=%d", len(f.Support), f.K)
	}

	dict := NewDictionary()
	for _, name := range f.Names {
		nb := []byte(name)
		dict.ApplyDelta(wire.DictDelta{ID: sketch.SeriesID(nb), Name: nb})
	}
	dict.ObserveEmitter(1)

	params := sketch.Params{M: f.M, D: f.D, Seed: f.Seed}
	opts := Options{
		Iters:            f.Iters,
		Lambda:           f.Lambda,
		PowerIters:       f.PowerIters,
		Threshold:        f.Threshold,
		EmittersExpected: 1,
	}

	res, err := Recover(f.Y, dict, params, opts)
	if err != nil {
		t.Fatalf("Recover: %v", err)
	}
	if res.Confidence != ConfidenceRecovered {
		t.Fatalf("Confidence = %q, want %q", res.Confidence, ConfidenceRecovered)
	}

	checkRecallAndRMSE(t, "recovery_case1", f.Support, res, 0.95, 0.05)
}

type recoveryWatermarkSection struct {
	EmitterID       int                  `json:"emitter_id"`
	Revision        int                  `json:"revision"`
	CoveragePresent int                  `json:"coverage_present"`
	CoverageTotal   int                  `json:"coverage_total"`
	Support         []goldenSupportEntry `json:"support"`
	Y               []float64            `json:"y"`
}

type recoveryWatermarkFile struct {
	M          int                      `json:"m"`
	D          int                      `json:"d"`
	Seed       uint64                   `json:"seed"`
	Lambda     float64                  `json:"lambda"`
	Threshold  float64                  `json:"threshold"`
	Iters      int                      `json:"iters"`
	PowerIters int                      `json:"power_iters"`
	Names      []string                 `json:"names"`
	Initial    recoveryWatermarkSection `json:"initial"`
	LateFrame  recoveryWatermarkSection `json:"late_frame"`
	Revised    recoveryWatermarkSection `json:"revised"`
}

// testGoldenRecoveryWatermark replays ADR-013's watermark/repair
// lifecycle: emitter A's window-100 frame arrives and is recovered at
// allowed_lateness (coverage 1/2, revision 0); emitter B's late frame then
// merges additively into the same window (sketch additivity) and the
// window is re-solved (coverage 2/2, revision 1). Both solves must
// recover their respective ground truth with recall >= 0.95.
func testGoldenRecoveryWatermark(t *testing.T) {
	var f recoveryWatermarkFile
	loadGoldenJSON(t, "recovery_watermark.json", &f)

	dict := NewDictionary()
	for _, name := range f.Names {
		nb := []byte(name)
		dict.ApplyDelta(wire.DictDelta{ID: sketch.SeriesID(nb), Name: nb})
	}

	params := sketch.Params{M: f.M, D: f.D, Seed: f.Seed}
	baseOpts := Options{
		Iters:            f.Iters,
		Lambda:           f.Lambda,
		PowerIters:       f.PowerIters,
		Threshold:        f.Threshold,
		EmittersExpected: f.Initial.CoverageTotal,
	}

	// Initial solve: only emitter A has arrived.
	dict.ObserveEmitter(uint64(f.Initial.EmitterID))
	opts1 := baseOpts
	opts1.Revision = f.Initial.Revision
	res1, err := Recover(f.Initial.Y, dict, params, opts1)
	if err != nil {
		t.Fatalf("Recover (initial): %v", err)
	}
	if res1.Revision != f.Initial.Revision {
		t.Fatalf("initial Revision = %d, want %d", res1.Revision, f.Initial.Revision)
	}
	if res1.Coverage != f.Initial.CoveragePresent || res1.CoverageTotal != f.Initial.CoverageTotal {
		t.Fatalf("initial Coverage = (%d,%d), want (%d,%d)", res1.Coverage, res1.CoverageTotal, f.Initial.CoveragePresent, f.Initial.CoverageTotal)
	}
	checkRecallAndRMSE(t, "recovery_watermark initial", f.Initial.Support, res1, 0.95, 0.05)

	// Late frame from emitter B arrives; the window is re-solved with the
	// merged y (ADR-013 additivity) and the revision counter increments.
	dict.ObserveEmitter(uint64(f.LateFrame.EmitterID))
	opts2 := baseOpts
	opts2.Revision = f.Revised.Revision
	res2, err := Recover(f.Revised.Y, dict, params, opts2)
	if err != nil {
		t.Fatalf("Recover (revised): %v", err)
	}
	if res2.Revision != f.Revised.Revision {
		t.Fatalf("revised Revision = %d, want %d", res2.Revision, f.Revised.Revision)
	}
	if res2.Revision == res1.Revision {
		t.Fatalf("revision counter did not increment: initial=%d revised=%d", res1.Revision, res2.Revision)
	}
	if res2.Coverage != f.Revised.CoveragePresent || res2.CoverageTotal != f.Revised.CoverageTotal {
		t.Fatalf("revised Coverage = (%d,%d), want (%d,%d)", res2.Coverage, res2.CoverageTotal, f.Revised.CoveragePresent, f.Revised.CoverageTotal)
	}

	combined := append(append([]goldenSupportEntry(nil), f.Initial.Support...), f.LateFrame.Support...)
	checkRecallAndRMSE(t, "recovery_watermark revised", combined, res2, 0.95, 0.05)
}

// checkRecallAndRMSE reproduces the oracle's own recall/relative-RMSE
// methodology (oracle/gen_golden.py: gen_recovery_case1/gen_recovery_watermark)
// against ground truth, over the intersection of ground-truth and
// recovered IDs.
func checkRecallAndRMSE(t *testing.T, label string, truth []goldenSupportEntry, res Result, minRecall, maxRelRMSE float64) {
	t.Helper()
	if len(truth) == 0 {
		t.Fatalf("%s: empty ground-truth support", label)
	}

	truthByID := make(map[uint64]float64, len(truth))
	for _, s := range truth {
		truthByID[s.ID] = s.Residual
	}
	recoveredByID := make(map[uint64]float64, len(res.SupportIDs))
	for i, id := range res.SupportIDs {
		recoveredByID[id] = res.Values[i]
	}

	var hit int
	var sumSqErr, sumSqTrue float64
	for id, trueVal := range truthByID {
		gotVal, ok := recoveredByID[id]
		if !ok {
			continue
		}
		hit++
		diff := gotVal - trueVal
		sumSqErr += diff * diff
		sumSqTrue += trueVal * trueVal
	}

	recall := float64(hit) / float64(len(truthByID))
	if recall < minRecall {
		t.Fatalf("%s: recall = %v (%d/%d), want >= %v", label, recall, hit, len(truthByID), minRecall)
	}
	if hit == 0 {
		return
	}
	relRMSE := math.Sqrt(sumSqErr/float64(hit)) / math.Sqrt(sumSqTrue/float64(hit))
	if relRMSE > maxRelRMSE {
		t.Fatalf("%s: relative RMSE = %v, want <= %v", label, relRMSE, maxRelRMSE)
	}
}

func loadGoldenJSON(t *testing.T, filename string, v interface{}) {
	t.Helper()
	const dir = "../../testdata/golden"
	path := dir + "/" + filename
	data, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("no golden vectors at %s: %v (run `make golden`)", path, err)
	}
	if err := json.Unmarshal(data, v); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
}
